name: Cypress Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (do not stop workflow)
        continue-on-error: true
        run: |
          npm run clean:reports
          npm run cy:run

      - name: Generate HTML report bundle
        if: always()
        run: |
          npm run report:merge
          npm run report:generate
          npm run report:customize
          npm run report:copy:screenshots

      - name: Upload FINAL HTML Report Bundle
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-html-report
          path: cypress/reports/html/**
          if-no-files-found: error

      - name: Upload Debug JSON (only if something fails)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: debug-json
          path: cypress/reports/**/*.json
          if-no-files-found: warn
